Prismic recursive rendering
DivanteLtd/next pull request #112
Opened 2020-01-15 14:06 UTC by defudef

2020-01-17 12:50 UTC, filrak requested changes
Prismic is not a part of commercetools so it shouldnt be a part of commercetools integration

2020-01-23 10:53 UTC, defudef commented on packages/commercetools/theme/components/prismic/CustomPage.vue
> +    {{blocks.length}}
```suggestion
```

2020-01-29 09:06 UTC, filrak requested changes

2020-01-29 09:06 UTC, filrak commented on packages/commercetools/theme/components/prismic/CustomPage.vue
> +    {{blocks.length}}
^^

2020-01-29 09:06 UTC, filrak commented on packages/commercetools/theme/package.json
> +    "@storefront-ui/vue": "file:../../../../storefront-ui/packages/vue",
Shoupd be 0.5.1

2020-01-30 08:42 UTC, defudef commented on packages/commercetools/theme/package.json
> +  "version": "1.0.1",
```suggestion
  "version": "0.0.3",
```

2020-01-30 08:46 UTC, filrak approved these changes

2020-01-30 09:02 UTC, merged