[WIP] Prismic as a package
DivanteLtd/next pull request #155
Opened 2020-02-04 18:26 UTC by defudef

2020-02-13 13:05 UTC, andrzejewsky requested changes

2020-02-13 13:05 UTC, andrzejewsky commented on packages/commercetools/theme/pages/Prismic.vue
> +    const { document, search, loading, error } = usePrismic()
`document` is a JS keyword, use something different instead, eg. `doc`

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicBlock.vue
> +const parseType = (block) => {
transform these functions into internal helpers

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicBlock.vue
> +const parseType = (block) => {
and add TS types for them & write test cases

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicBlock.vue
> +    const { type, document } = transformBlock(block)
this should be part of the composable... 
```
const { document } = usePrismic()
```

and the `render` or `renderBlock` - sounds like public helper (`getPrismicBlock`)

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicBlock.vue
> +    const { type, document } = transformBlock(block)
import { getPrismicBlock } from '@vue-storefront/prismic/helpers'
import { usePrismic } from '@vue-storefront/prismic/composables'

```
setup() {
   const { document } = usePrismic()

  return { document, getPrismicBlock}
}
```
and template:

```
<tepmlate>
<div>{{ getPrismicBlock(document) }}</div>
</template>
```

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicBlock.vue
> +    const { type, document } = transformBlock(block)
+ ofc unit test for the helper

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/components/PrismicDocument.vue
> +const parseType = (document) => {
exactly the same in here: internal helper, unit tests, etc.

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/src/composables/usePrismic/index.ts
> +      switch (true) {
????

2020-02-13 13:05 UTC, andrzejewsky commented on packages/prismic/src/interfaces.ts
> +type DateValue = string | number | Date
directory types/index.ts as in others

2020-02-13 15:52 UTC, defudef commented on packages/prismic/src/composables/usePrismic/index.ts
> +      switch (true) {
Instead of having tons of ifs I've written switch true. I've seen this approach several times

2020-02-13 16:06 UTC, defudef commented on packages/prismic/components/PrismicBlock.vue
> +    const { type, document } = transformBlock(block)
I can agree `document` isn't the correct name for the block content. `element` sounds better so I'll change it.

Also, every other package uses helper only inside composables so we should keep a convention.

The important thing is, I don't want to share the rendering method "globally". This is only a "ready to go" solution. You can but you're not forced to render every block in this way.

2020-02-18 07:21 UTC, EugeneHlushko reviewed
Hi @defudef 
It would be nice to get it documented or extend PR description with key points so its easier to review, from code perspective it looks good despite slices and `doc.body` being a TODO :)

2020-02-18 13:47 UTC, defudef commented
> Hi @defudef
> It would be nice to get it documented or extend PR description with key points so its easier to review, from code perspective it looks good despite slices and `doc.body` being a TODO :)

Working on that now as separate PR :)

2020-02-19 09:24 UTC, andrzejewsky approved these changes

2020-02-19 09:32 UTC, merged