Language selector
DivanteLtd/next pull request #165
Opened 2020-02-10 14:36 UTC by andrzejewsky

2020-02-11 11:34 UTC, filrak requested changes

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/api-client/src/index.ts
> +let countries = ['UK', 'US']
get rid of that

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/api-client/src/index.ts
> +  countries = setupConfig.countries || countries
that too

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/composables/src/useLocales/index.ts
> +import { ref, Ref, computed, watch } from '@vue/composition-api'
Singular useLocale

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/composables/src/useLocales/index.ts
> +  const locale: Locale = ref(context.root.$i18n.locale)
get rid of context

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/composables/src/useLocales/index.ts
> +  const availableLocales: AvailableLocales = computed<string[]>(() => context.root.$i18n.availableLocales)
check convention

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/composables/src/useLocales/index.ts
> +    console.log('changed currency', currency.value)
remove console log

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/composables/src/useLocales/index.ts
> +    Cookies.set('vsf-country', country.value)
cookie name via config

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/theme/components/LanguageSelector.vue
> +      availableLocales,
smarter return

2020-02-11 11:34 UTC, filrak commented on packages/commercetools/theme/components/TopBar.vue
> +      <language-selector />
```suggestion
      <LanguageSelector />
```

2020-02-12 09:12 UTC, defudef commented on packages/commercetools/api-client/src/index.ts
> +  locale = setupConfig.locale || locale
setupConfig can be undefined and this will throw an error `cannot ready property locale of undefined`

2020-02-12 09:12 UTC, defudef commented on packages/commercetools/theme/config.js
> +    { name: 'USD', label: 'Dollar' },
IMO it's better to use just "EUR" and "USD" in this case, or you should rename it to "American Dollar"

2020-02-16 16:29 UTC, merged