DI-5304: create api client integration for cart
DivanteLtd/next pull request #260
Opened 2020-03-16 10:48 UTC by I2olanD

- [ ] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

2020-03-16 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/next?pullRequest=260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/next?pullRequest=260) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/next?pullRequest=260) it.</sub>

2020-03-16 11:44 UTC, filrak commented
Please accept CLA :)

2020-03-16 12:17 UTC, I2olanD commented
> Please accept CLA :)

done :)

2020-03-17 07:40 UTC, lukeromanowicz requested changes
The code looks good to me but we need to improve test coverage

2020-03-17 07:46 UTC, lukeromanowicz requested changes

2020-03-17 07:46 UTC, lukeromanowicz commented on packages/about-you/api-client/tests/api/removeFromCart/index.spec.ts
> +apiClient.basket.deleteItem = mockDeleteItem;
This isn't really how you should mock apiClient. I suggest to use jest.mock instead.

2020-03-17 07:46 UTC, lukeromanowicz commented on packages/about-you/api-client/tests/api/clearCart/index.spec.ts
> +    apiClient.basket.get = mockGetBasket;
This isn't really how you should mock apiClient. I suggest to use jest.mock instead.

2020-03-20 10:03 UTC, lukeromanowicz approved these changes
I am truly impressed by how quickly you have adapted to this way of writing unit tests. Awesome job @I2olanD!

2020-03-20 11:38 UTC, filrak approved these changes

2020-03-26 09:44 UTC, andrzejewsky approved these changes

2020-03-26 09:44 UTC, merged