change interfaces to comply with paginated search results
DivanteLtd/next pull request #265
Opened 2020-03-17 19:31 UTC by Qrzy

Search results in `useProduct` and `useUserAddress` can be paginated, hence this change that follows the way the `useUserOrders` has been prepared for pagination.

2020-03-18 09:04 UTC, andrzejewsky requested changes

2020-03-18 09:04 UTC, andrzejewsky commented on packages/core/interfaces/src/index.ts
> +  products: {
please use `products` and `totalProducts` instead

2020-03-18 09:04 UTC, andrzejewsky commented on packages/core/interfaces/src/index.ts
> +  addresses: {
same here `addressess` and` totalAddressess`

2020-03-18 09:20 UTC, patzick requested changes
Just one note + point from @andrzejewsky

2020-03-18 09:20 UTC, patzick commented on packages/core/factories/src/useProductFactory.ts
> +
```suggestion
export type SearchResult<T> = {
  data: T[];
  total: number;
};

```

2020-03-18 09:20 UTC, patzick commented on packages/core/factories/src/useProductFactory.ts
> +
this can be used for all searches

2020-03-18 14:49 UTC, patzick requested changes
Just one thing from me :)

2020-03-18 14:49 UTC, patzick commented on packages/core/factories/src/index.ts
> +
```suggestion
```

this shouldn't be here

2020-03-19 08:25 UTC, patzick approved these changes
👍

2020-03-19 08:40 UTC, andrzejewsky approved these changes

2020-03-19 08:43 UTC, merged