Feature/ay integration
DivanteLtd/next pull request #276
Opened 2020-03-19 15:11 UTC by I2olanD

- [x] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

2020-03-19 15:18 UTC, lukeromanowicz requested changes

2020-03-19 15:18 UTC, lukeromanowicz commented on packages/about-you/composables/__tests__/useCategory/index.spec.ts
> +    expect(useCategory).toBeInstanceOf(Function);
the test below tests also the same thing as this one

2020-03-19 15:18 UTC, lukeromanowicz commented on packages/about-you/composables/__tests__/useProduct/index.spec.ts
> +    expect(useProduct).toBeInstanceOf(Function);
same here :)

2020-03-19 15:27 UTC, lukeromanowicz approved these changes

2020-03-20 08:18 UTC, filrak approved these changes

2020-03-20 08:19 UTC, filrak commented on packages/about-you/composables/src/composables/useProduct/index.ts
> +  productsSearch: enhanceProduct
i dont think its enhancing anything, juz mapping, maybe its better to call it `mapProductSearch` ?

2020-03-20 08:53 UTC, merged