Fix SSR issues, new API
DivanteLtd/next pull request #277
Opened 2020-03-19 16:03 UTC by andrzejewsky

- [x] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

2020-03-24 09:01 UTC, filrak requested changes

2020-03-24 09:01 UTC, filrak commented on packages/core/theme-module/theme/pages/Category.vue
> +  asyncData() {
wtf?

2020-03-24 09:02 UTC, andrzejewsky commented on packages/core/theme-module/theme/pages/Category.vue
> +  asyncData() {
ić stont, WIP!!

2020-03-24 15:56 UTC, patzick requested changes
Tho small changes from me, overriding this looks 👌

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +type Handler = (value?: any) => void;
as this is exposed as external param, should be exported as well
```suggestion
export type Handler = (value?: unknown) => void;
```

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +}
I believe we don't need this one, methods exports same interface
```suggestion
```

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +const emit = (eventName: string, value: any): void => {
```suggestion
export function emit (eventName: string, value: any): void {
```

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +let emitted: Event[] = [];
we should move it under types declaration, but before exported functions

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +const on = (eventName: string, handler: Handler): void => {
```suggestion
export function on (eventName: string, handler: Handler): void {
```

2020-03-24 15:56 UTC, patzick commented on packages/core/utils/src/event-bus/index.ts
> +export default eventBus;
we're exporting methods directly
```suggestion
```

2020-03-24 15:56 UTC, patzick commented on packages/core/factories/src/useCategoryFactory.ts
> +    const { state } = useSSR(cacheId);
would be nice to have instead
```
const { state, setCache } = useSSR(cacheId) 
```
then it's just call
```
setCache(categories.value)
```
and even cacheId is set at this point internally

2020-03-24 15:56 UTC, patzick commented on packages/core/factories/src/useCategoryFactory.ts
> +      eventBus.emit('set-ssr-cache', { key: cacheId, value: categories.value });
after other comment
```suggestion
      setCache(categories.value)
```
wdyt @andrzejewsky @filrak ?

2020-03-24 15:56 UTC, patzick commented on packages/core/factories/src/useCategoryFactory.ts
> +      }
this is not necessary :) 
```suggestion
      loading.value = true;
```

2020-03-24 15:56 UTC, patzick commented on packages/core/factories/src/useProductFactory.ts
> +    const search = async (params: any) => {
why is that?
we need to use `PRODUCT_SEARCH_PARAMS` here :)
```suggestion
    const search = async (params: PRODUCT_SEARCH_PARAMS) => {
```

2020-03-24 19:46 UTC, andrzejewsky commented on packages/core/utils/src/event-bus/index.ts
> +type Handler = (value?: any) => void;
noo this is only for internal usage, it's not used anywhere

2020-03-25 08:15 UTC, filrak requested changes
Regarding API ( `saveToCache` seems like the right one and if we're saving to cache then we should retrieve `cache`, not state (or the opposite we should save to `state` not cache)

2020-03-25 08:15 UTC, filrak commented on packages/core/docs/core/utils/server-side-rendering.md
> +export function useExampleFactory(factoryParams) {
imo factory here is not needed and just adds redundant complexity, just show how to use it with some example use case (using `example` is not the best way to explain stuff as well, show something that can be understood as an idea - simplified product comparable or so)

2020-03-25 08:22 UTC, filrak commented on packages/core/theme-module/theme/components/RelatedProducts.vue
> +  setup() {
shouldn't setup be always on top?

2020-03-25 08:56 UTC, filrak approved these changes

2020-03-25 10:27 UTC, merged