feat(core): Apiclientfactory
DivanteLtd/next pull request #290
Opened 2020-03-24 13:50 UTC by filrak

- [x] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

2020-03-26 15:09 UTC, andrzejewsky requested changes
looks ok 👍 just one comment and look what's wrong with the build

2020-03-26 15:09 UTC, andrzejewsky commented on packages/core/factories/src/apiClientFactory.ts
> +  let settings = { ...factoryParams.defaultSettings };
```
let settings = { ...factoryParams.defaultSettings, overrides: {} };
```

2020-03-27 08:51 UTC, patzick approved these changes
I'd need to see the use case for this factory, but overall looks okay to me :)

2020-03-27 08:51 UTC, patzick commented on packages/core/factories/src/apiClientFactory.ts
> +    getSettings: () => Object.freeze(settings)
this should return type with `API_CLIENT_SETTINGS ` for IDE

2020-03-27 09:23 UTC, andrzejewsky approved these changes

2020-03-27 11:59 UTC, merged