Configurations
DivanteLtd/next pull request #3
Opened 2019-10-27 21:01 UTC by andrzejewsky

2019-10-28 09:24 UTC, filrak requested changes

2019-10-28 09:24 UTC, filrak commented on packages/core/index.ts
> +  loading: any;
czemu tak?

2019-10-28 09:24 UTC, filrak commented on packages/composables/src/hooks/useProduct/index.ts
> +    lastConfiguration,
lastConfiguration - po co?
getPossibleOptions - tego nie ma w `products` latwo do wyssania?

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/BundleProductDetails.vue
> +const createInitialValues = (productOptions) =>
dalbys rade okomentowac cel tego?

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/BundleProductDetails.vue
> +import { watch, ref, reactive, toRefs } from '@vue/composition-api'
```suggestion
import { reactive } from '@vue/composition-api'
```

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ProductDetails.vue
> +<template>
to albo mozemy te 2 poprzednie komponenty tutaj zamknac i wyifowac (mniejszy cognitive overload z lataniem po plikach) albo wyifowac je w product page

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ProductDetails.vue
> +import { computed, ref, watch } from '@vue/composition-api'
```suggestion
import { computed } from '@vue/composition-api'
```

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ConfigurableProductDetails.vue
> +import { computed, ref, watch } from '@vue/composition-api'
```suggestion
import { computed, ref } from '@vue/composition-api'
```

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ConfigurableProductDetails.vue
> +      const sizeOptions = productOptions.find(o => o.attributeName === 'size')
co jesli jest wiecej niz size i color? Musimy to miec jakos zautmatyzowane najlepiej 1 propertiesem

2019-10-28 09:24 UTC, filrak commented on packages/theme/pages/product/_sku.vue
> +    apiSetup({
to w /plugins ;)

2019-10-28 09:24 UTC, filrak commented on packages/theme/pages/product/_sku.vue
> +    const handleChange = (configuration) => {
nazwa funkcji nic nie mowi o tym co robi, imo wgl powinnismy uzywac tu po prostu `configure` bez wrapowania 1 funkcji w kolejna zeby zahardkodowac 1 argument

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/BundleProductDetails.vue
> +<template>
dalbys rade tutaj tylko dane zostawic bez ui?

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/BundleProductDetails.vue
> +<template>
nazwa komponentu powinna byc jak juz chyba bundleProductOprions

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ConfigurableProductDetails.vue
> +<template>
tutaj tez nazwa srednio deskryptywna

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ConfigurableProductDetails.vue
> +    const handleChange = () => {
`handleConfigurableOptionChange` ? albo cos innego opisujacego co tu sie dzieje

2019-10-28 09:24 UTC, filrak commented on packages/theme/components/ConfigurableProductDetails.vue
> +      emit('input', configuration)
`input` to nie jest dobry event na to co sie tutaj dzieje

2019-10-28 09:24 UTC, filrak commented on packages/theme/pages/product/_sku.vue
> +    const testSku = 'WS09' // '24-WG080' // WS09
unikajmy takich rzeczy bo pozniej czesto przypadkiem zostaja ;) po prostu zahardkofuj do `search`

2019-10-28 09:24 UTC, filrak commented on packages/theme/pages/product/_sku.vue
>        detailsIsActive: false
?

2019-10-28 09:24 UTC, filrak commented on packages/theme/pages/product/_sku.vue
>        properties: [
?

2019-10-28 09:29 UTC, andrzejewsky commented on packages/core/index.ts
> +  loading: any;
chwilowo, wlasnie dobrze ze o tym mowisz: tam powinno byc `Ref<boolean>` tak samo z error, dalem `any` chwilowo zeby mi sie po prostu kompilowalo

2019-10-28 09:30 UTC, andrzejewsky commented on packages/core/index.ts
> +  loading: any;
generalnie wszedzle tam mozna dac `Ref<T>` np. `Ref<PRODUCTS>`

2019-10-28 09:32 UTC, andrzejewsky commented on packages/composables/src/hooks/useProduct/index.ts
> +    lastConfiguration,
`lastConfiguration` - ostatni produkt jaki konfigurowales, na produkt page to akurat nawet przydatne bo nie musisz grzebac po tablicy `currentConfiguration`
`getPossibleOptions` - da Ci dostepne opcje jakie masz z danego produktu czyli mp. dostepne kolory, dostepne rozmiary, tak samo z bundle'ami dostepne opcje, z tym ze one wzystkie sa sprowadzone do jednego formatu

2019-10-28 09:33 UTC, andrzejewsky commented on packages/composables/src/hooks/useProduct/index.ts
> +    lastConfiguration,
zastanawiam sie czy po prostu nie wepchac pola do kazdego z produktow z opcjami ktore mozesz wysiwietlic juz sprowadzone do formatu taki jaki chce UI, mozna to wtedy przeniesc pozniej do API nawet - co myslisz?

2019-10-28 09:34 UTC, andrzejewsky commented on packages/theme/components/BundleProductDetails.vue
> +const createInitialValues = (productOptions) =>
tylko i wylacznie taki helper zeby opcje do bundla wyswietlic, nie jest to nigdzie wiecej potrzebne wiec jak bedziesz zmienial te widoki to moze Ci byc nie potrzebne

2019-10-28 09:35 UTC, andrzejewsky commented on packages/theme/components/BundleProductDetails.vue
> +import { watch, ref, reactive, toRefs } from '@vue/composition-api'
wszystkie importy pozmieniam, spokojnie :D

2019-10-28 12:32 UTC, filrak commented on packages/composables/src/hooks/useProduct/index.ts
> +    lastConfiguration,
to tez tymi helperami mozemy ogarnac getAvailableOptions(product). Zastanawiam sie co bedzie lepsze bo Twoj pomysl jest latwiejszy do ogarniecie przez deva chyba, tylko moze pompowac wieksze responsey przez duplikacje

2019-10-29 08:39 UTC, pkarw commented
Panowie - na szybko przejrzałem i mam uwagi odnośnie namingu:
- possible -> available - nikt nie używa słowa `possible` - to znaczy coś typu "co co jet możliwe" w sensie zdarzenia;
- `currentProduct`, `product` itd. - IMO powinniśmy mieć jakąś konwencję nazewnictwa (spisać ją od myślników); im mniej adjectives i prostsze nazwy tym IMO lepiee; propozycja:
`currentProduct` -> `product`
`availableOptions` -> `options`
`lastConfiguration` -> trudno zrozumieć, co w niej jest - czy jest to potrzebne na poziomie hooka?
`curentConfigurations` -> trudno zrozumieć co to jest, czy jest to potrzebne? jeśli tak to chyba powinno si inaczej nazywać

Wydaje mi się, że to co my nazywamy konfiguracjami to są .. .warianty? :) W sensie w innych platformach.

Naming w hookach to jest to miejsce, gdzie wprowadzamy `platform agnosticity`. W sensie - najlepiej żeby te rzeczy zwracane przez hooki pasowały do innych platform.

Benchmark który powinniśmy wziąc pod uwagę:
- https://developer.bigcommerce.com/api-docs/catalog/products-overview#variant
- https://help.shopify.com/en/api/reference/products/product-variant
- https://docs.commercetools.com/http-api-projects-products#ProductVariant

Te 3 API są uznawane obecnie za totalny benchmark i najlepszy wzorzec API dla eCommerce

Ogólnie rzecz biorąc - na ile to możliwe warto też wzorować się na tym co już sami mamy czyli: https://github.com/DivanteLtd/shopware-pwa/tree/master/packages/shopware-6-client/src/services


Chodzi mi głównie o interfejs dla programisty - czyli to, co zwracają hooki.

2019-10-29 09:27 UTC, filrak commented on packages/composables/src/helpers/index.ts
> +  getPossibleOptions,
getAvailableOptiosn chyba lepiej

2019-10-29 18:45 UTC, filrak commented on packages/composables/src/helpers/index.ts
> +  createProductConfiguration,
tez dziwnie brzmi, co to robi?

2019-10-29 18:45 UTC, filrak commented on packages/composables/src/helpers/product/createProductOption.ts
> +}) as any
![image](https://user-images.githubusercontent.com/15185752/67798880-a311f180-fa84-11e9-86da-981068ccc90e.png)

2019-11-05 09:15 UTC, merged

2019-11-05 09:20 UTC, filrak commented on packages/api-client/src/types/Product.ts
> +export interface ProductConfigurableChildrenItem {
to item jest tu potrzebne? dobrze ogolnei jakas konwencje nazewnictwa miec, moze siadziemy i pokminimy?

2019-11-05 09:20 UTC, filrak commented on packages/api-client/src/types/Product.ts
> +export interface ProductConfigurableOptionItem {
again, moze po prostu bez item

2019-11-05 09:20 UTC, filrak commented on packages/api-client/src/types/Product.ts
> +export interface BundleOptionProductLink {
tutaj ustalilismy zmiany tez

2019-11-05 09:20 UTC, filrak commented on packages/api-client/src/types/Product.ts
> +export interface BundleItemOptions {
nie jest dla mnie jasne czym jest `BundleOptionItem` a czym `BundleItemOptions`, czasem mozna wgl pododawac male anotacje jak nazwa nie jest wystarczajaca

2019-11-05 09:20 UTC, filrak commented on packages/composables/raw.ts
> +  getOptions
wgl rawa wywal i dossaj zmiany, teraz z pola `module` w pkg.json bierze rawa