feat(ssr): Disabling ssr
DivanteLtd/next pull request #330
Opened 2020-03-31 19:24 UTC by andrzejewsky

- [x] I Accept [Individual Contributor License Agreement](https://github.com/DivanteLtd/next/blob/master/CLA.md)

2020-03-31 19:25 UTC, filrak approved these changes

2020-03-31 19:30 UTC, filrak commented
I like the idea, please take my okejka

2020-03-31 19:45 UTC, Qrzy approved these changes

2020-04-01 22:03 UTC, filrak commented
Lets do as we discussed, and just have a `load` function`. Can you update the RFC to mirror our target API @andrzejewsky ?

2020-04-01 22:03 UTC, filrak requested changes
Change to discussed API

2020-04-08 22:51 UTC, closed without merging