Implement getProduct
DivanteLtd/next pull request #47
Opened 2019-12-10 22:16 UTC by andrzejewsky

2019-12-10 22:18 UTC, andrzejewsky commented on packages/commercetools/theme/pages/index.vue
> +    getProduct({ variables: {
@filrak example how to use it, I'll implement a generic helpers (eg. `getWhereByCatId`, `getWhereByCatSlug` etc.) to generate `where` param

2019-12-11 12:46 UTC, filrak requested changes

2019-12-11 12:46 UTC, filrak commented on packages/commercetools/api-client/src/api/getProduct/defaultQuery.ts
> +import gql from 'graphql-tag'
can't we just use gql files?

2019-12-11 12:46 UTC, filrak commented on packages/commercetools/api-client/src/helpers/createCommerceToolsLink/getAccessToken.ts
> +import { ApiConfig } from 'api-client/src/types/setup'
maybe it's better to just use '@' alias for root as common convention

2019-12-11 12:46 UTC, filrak commented on packages/commercetools/api-client/src/helpers/i18n/index.ts
> +const getCurrency = () => 'USD'
Imho it's better to keep it from config passed into `setup` then in the app you can set reference to currency and locale fields. It's also better to keep all configuration in one place

2019-12-11 13:40 UTC, merged